name: Comment on Failed Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spec_doc_generator:
    name: Check Generator Templates
    runs-on: ubuntu-24.04
    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@56684e85b94c6340f5035965d57dcfdedd1ab0de
        with:
          crystal: "1.15.1"
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Run generator tests
        run: crystal spec ./document-generator/spec/*
  comment_on_failed_test:
    permissions: write-all
    name: Check Generator Templates
    runs-on: ubuntu-24.04
    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@56684e85b94c6340f5035965d57dcfdedd1ab0de
        with:
          crystal: "1.15.1"
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Run generator tests
        run: crystal document-generator/scripts/check_docs.cr
      - name: Comment on PR if test failed
        if: failure()
        uses: exercism/pr-commenter-action@v1.5.1
        with:
          github-token: ${{github.token}}
          config-file: ".github/pr-commenter.yml"
          